@PcWarehoseApi_HostAddress = http://localhost:5149

GET {{PcWarehoseApi_HostAddress}}/weatherforecast/
Accept: application/json

###

### Get all pcs
GET {{PcWarehoseApi_HostAddress}}/api/pcs

### Get pc with components
GET {{PcWarehoseApi_HostAddress}}/api/pcs/1/components

### Get non-existing pc with components
GET {{PcWarehoseApi_HostAddress}}/api/pcs/999/components


### Create pc
POST {{PcWarehoseApi_HostAddress}}/api/pcs
Content-Type: application/json

{
  "name": "Gaming Beast X",
  "weight": 12.5,
  "warranty": 36,
  "createdAt": "2026-05-08T09:00:00",
  "stock": 5
}

### Update pc
PUT {{PcWarehoseApi_HostAddress}}/api/pcs/1
Content-Type: application/json

{
  "name": "Gaming Beast X Updated",
  "weight": 13.0,
  "warranty": 48,
  "createdAt": "2026-05-08T09:00:00",
  "stock": 7
}

### Delete pc without components
DELETE {{PcWarehoseApi_HostAddress}}/api/pcs/999

### Delete existing pc
DELETE {{PcWarehoseApi_HostAddress}}/api/pcs/1